// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vegbhakginvysiaaqnatk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ2JoYWtnaW52eXNpYXFuYXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzAzNDksImV4cCI6MjA2OTkwNjM0OX0.7MKFmLnfKv8s0LsclMTeX-9IBMLt2Rg_xPFjNjuxDS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'CallGenie'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 2
    }
  }
});